export type MusicStyle =
  | "lullaby"
  | "upbeat_kids"
  | "classical_indian"
  | "folk_indian"
  | "pop_kids";

export interface MusicRequest {
  lyrics: string;
  style: MusicStyle;
  duration?: number;
  instrumental?: boolean;
}

export interface MusicResponse {
  taskId: string;
  status: "pending" | "processing" | "complete" | "error";
  audioUrl?: string;
  title?: string;
  duration?: number;
  errorMessage?: string;
}

export const MUSIC_STYLES: Record<
  MusicStyle,
  { label: string; description: string; sunoTag: string }
> = {
  lullaby: {
    label: "Lullaby",
    description: "Soft, soothing melodies for bedtime",
    sunoTag: "gentle lullaby, soft piano, soothing, children",
  },
  upbeat_kids: {
    label: "Upbeat Kids",
    description: "Fun, energetic tunes for playtime",
    sunoTag: "upbeat children song, happy, playful, clapping",
  },
  classical_indian: {
    label: "Classical Indian",
    description: "Traditional ragas adapted for children",
    sunoTag: "indian classical, sitar, tabla, melodic, children friendly",
  },
  folk_indian: {
    label: "Folk Indian",
    description: "Regional folk music styles",
    sunoTag: "indian folk, dholak, flute, festive, kids",
  },
  pop_kids: {
    label: "Pop Kids",
    description: "Modern pop for young audiences",
    sunoTag: "kids pop, catchy, modern, synthesizer, fun",
  },
};

// Free kids music samples organized by style
const STYLE_AUDIO_URLS: Record<MusicStyle, string[]> = {
  lullaby: [
    "https://cdn.pixabay.com/audio/2024/02/14/audio_8e2a50c527.mp3",
    "https://cdn.pixabay.com/audio/2022/10/18/audio_29e6e4a475.mp3",
  ],
  upbeat_kids: [
    "https://cdn.pixabay.com/audio/2024/08/27/audio_e0767fccb5.mp3",
    "https://cdn.pixabay.com/audio/2022/10/18/audio_29e6e4a475.mp3",
  ],
  classical_indian: [
    "https://cdn.pixabay.com/audio/2024/02/14/audio_8e2a50c527.mp3",
    "https://cdn.pixabay.com/audio/2024/08/27/audio_e0767fccb5.mp3",
  ],
  folk_indian: [
    "https://cdn.pixabay.com/audio/2022/10/18/audio_29e6e4a475.mp3",
    "https://cdn.pixabay.com/audio/2024/08/27/audio_e0767fccb5.mp3",
  ],
  pop_kids: [
    "https://cdn.pixabay.com/audio/2024/08/27/audio_e0767fccb5.mp3",
    "https://cdn.pixabay.com/audio/2024/02/14/audio_8e2a50c527.mp3",
  ],
};

function isMockMode(): boolean {
  return !process.env.SUNO_API_KEY;
}

export async function generateMusic(
  req: MusicRequest
): Promise<MusicResponse> {
  const taskId = `task_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;

  if (isMockMode()) {
    // In mock mode, return complete immediately with a sample track
    // This works on Vercel serverless (no setTimeout needed)
    const styleUrls = STYLE_AUDIO_URLS[req.style] || STYLE_AUDIO_URLS.lullaby;
    const audioUrl = styleUrls[Math.floor(Math.random() * styleUrls.length)];

    return {
      taskId,
      status: "complete",
      audioUrl,
      title: `${MUSIC_STYLES[req.style].label} - Generated`,
      duration: req.duration || 30,
    };
  }

  // Real Suno API call
  const styleInfo = MUSIC_STYLES[req.style];
  const response = await fetch(`${process.env.SUNO_API_URL}/api/generate`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${process.env.SUNO_API_KEY}`,
    },
    body: JSON.stringify({
      prompt: req.lyrics,
      tags: styleInfo.sunoTag,
      make_instrumental: req.instrumental ?? false,
      wait_audio: false,
    }),
  });

  if (!response.ok) {
    return { taskId, status: "error", errorMessage: "Failed to start generation" };
  }

  const data = await response.json();
  const sunoId = data[0]?.id || taskId;

  return {
    taskId: sunoId,
    status: "processing",
    title: data[0]?.title || `${styleInfo.label} Track`,
  };
}

export async function getStatus(taskId: string): Promise<MusicResponse> {
  if (isMockMode()) {
    // In mock mode, if the taskId starts with task_, it was generated by us
    // Return complete with a random audio URL
    return {
      taskId,
      status: "complete",
      audioUrl: STYLE_AUDIO_URLS.lullaby[0],
      title: "Generated Track",
      duration: 30,
    };
  }

  // Real Suno API status check
  const response = await fetch(
    `${process.env.SUNO_API_URL}/api/get?ids=${taskId}`,
    {
      headers: {
        Authorization: `Bearer ${process.env.SUNO_API_KEY}`,
      },
    }
  );

  if (!response.ok) {
    return { taskId, status: "error", errorMessage: "Status check failed" };
  }

  const data = await response.json();
  const track = data[0];

  if (!track) {
    return { taskId, status: "error", errorMessage: "Track not found" };
  }

  return {
    taskId,
    status: track.status === "complete" ? "complete" : "processing",
    audioUrl: track.audio_url,
    title: track.title,
    duration: track.duration,
  };
}

export function getAudioUrl(taskId: string): string | undefined {
  return STYLE_AUDIO_URLS.lullaby[0];
}
